local_costmap:
    global_frame: /ropod_{id}/odom
    robot_base_frame: /ropod_{id}/base_link
    update_frequency: 1.0
    publish_frequency: 1.0
    static_map: false
    rolling_window: true
    width: 6.0
    height: 6.0
    resolution: 0.1
